/**
 * Wrap Quasar UI library to use as ES6 module in TeqFW on the front.
 *
 * @namespace TeqFw_Ui_Quasar_Front_Lib
 * TODO: rename to _Ext (as in vue-plugin)
 */
if (window.Quasar === undefined) {
    throw new Error(`
Add

<script type="application/javascript" src="./src/quasar/quasar.umd.prod.js"></script>
<script type="application/javascript" src="./src/quasar/icon-set/svg-material-icons.umd.prod.js"></script>
<link rel="stylesheet" href="./src/quasar/quasar.prod.css">

to your startup HTML to use Quasar UI.           
`);
}

//
/**
 * {@link https://next.quasar.dev/vue-components/dialog#qdialog-api QDialog API}
 * @typedef TeqFw_Ui_Quasar_Front_Lib.QDialog
 * @method focus
 * @method hide
 * @method shake
 * @method show
 * @method toggle
 */

// export corresponds to Quasar UI v. 2.3.3:
export const {
    AddressbarColor,
    AppFullscreen,
    AppVisibility,
    BottomSheet,
    clone,
    ClosePopup,
    colors,
    Cookies,
    copyToClipboard,
    createMetaMixin,
    createUploaderComponent,
    Dark,
    date,
    debounce,
    Dialog,
    dom,
    event,
    exportFile,
    extend,
    format,
    frameDebounce,
    getCssVar,
    iconSet,
    install,
    Intersection,
    lang,
    Loading,
    LoadingBar,
    LocalStorage,
    Meta,
    Morph,
    morph,
    Mutation,
    noop,
    Notify,
    openURL,
    patterns,
    Platform,
    QAjaxBar,
    QAvatar,
    QBadge,
    QBanner,
    QBar,
    QBreadcrumbs,
    QBreadcrumbsEl,
    QBtn,
    QBtnDropdown,
    QBtnGroup,
    QBtnToggle,
    QCard,
    QCardActions,
    QCardSection,
    QCarousel,
    QCarouselControl,
    QCarouselSlide,
    QChatMessage,
    QCheckbox,
    QChip,
    QCircularProgress,
    QColor,
    QDate,
    QDialog,
    QDrawer,
    QEditor,
    QExpansionItem,
    QFab,
    QFabAction,
    QField,
    QFile,
    QFooter,
    QForm,
    QFormChildMixin,
    QHeader,
    QIcon,
    QImg,
    QInfiniteScroll,
    QInnerLoading,
    QInput,
    QIntersection,
    QItem,
    QItemLabel,
    QItemSection,
    QKnob,
    QLayout,
    QLinearProgress,
    QList,
    QMarkupTable,
    QMenu,
    QNoSsr,
    QOptionGroup,
    QPage,
    QPageContainer,
    QPageScroller,
    QPageSticky,
    QPagination,
    QParallax,
    QPopupEdit,
    QPopupProxy,
    QPullToRefresh,
    QRadio,
    QRange,
    QRating,
    QResizeObserver,
    QResponsive,
    QRouteTab,
    QScrollArea,
    QScrollObserver,
    QSelect,
    QSeparator,
    QSkeleton,
    QSlideItem,
    QSlider,
    QSlideTransition,
    QSpace,
    QSpinner,
    QSpinnerAudio,
    QSpinnerBall,
    QSpinnerBars,
    QSpinnerBox,
    QSpinnerClock,
    QSpinnerComment,
    QSpinnerCube,
    QSpinnerDots,
    QSpinnerFacebook,
    QSpinnerGears,
    QSpinnerGrid,
    QSpinnerHearts,
    QSpinnerHourglass,
    QSpinnerInfinity,
    QSpinnerIos,
    QSpinnerOrbit,
    QSpinnerOval,
    QSpinnerPie,
    QSpinnerPuff,
    QSpinnerRadio,
    QSpinnerRings,
    QSpinnerTail,
    QSplitter,
    QStep,
    QStepper,
    QStepperNavigation,
    QTab,
    QTable,
    QTabPanel,
    QTabPanels,
    QTabs,
    QTd,
    QTh,
    QTime,
    QTimeline,
    QTimelineEntry,
    QToggle,
    QToolbar,
    QToolbarTitle,
    QTooltip,
    QTr,
    QTree,
    QUploader,
    QUploaderAddTrigger,
    QVideo,
    QVirtualScroll,
    Ripple,
    Screen,
    Scroll,
    scroll,
    ScrollFire,
    SessionStorage,
    setCssVar,
    throttle,
    TouchHold,
    TouchPan,
    TouchRepeat,
    TouchSwipe,
    uid,
    useDialogPluginComponent,
    useFormChild,
    useMeta,
    useQuasar,
    version,
} = window.Quasar;
